### ISSUE TITLE
Readme porting guide link is broken

### ISSUE THREAD

**Issue by prasad-dot-ws** [lvgl/lv_drivers#101]
The link in readme document for LVGL porting guide is broken. https://littlevgl.com/porting

Also the one which comes in google search also broken. https://docs.lvgl.io/en/html/porting/index.html

**Comment by embeddedt** [comment]
I fixed the one in the README. I can't do much about Google, but it should pick up on the new link within a few weeks. I don't know how frequently the site gets reindexed.

**Comment by prasad-dot-ws** [comment]
> I fixed the one in the README. I can't do much about Google, but it should pick up on the new link within a few weeks. I don't know how frequently the site gets reindexed.

Thanks @embeddedt for the instant reply.
