### ISSUE TITLE
Cannot build with evdev enabled

### ISSUE THREAD

**Issue by tmitchell-dev** [lvgl/lv_drivers#133]
I am trying to port to a Raspberry Pi 4 using gcc compiler.

Attempting to build with evdev enabled yields the following error:
`/home/pi/lvgl-test/lv_drivers/indev/evdev.c:228:42: error: ‘drv->disp->driver’ is a pointer; did you mean to use ‘->’?`

Changing lines 228-231 in evdev.c to use to arrow operator instead of dot operator fixes the issue on my end.
`    if(data->point.x >= drv->disp->driver->hor_res)
      data->point.x = drv->disp->driver->hor_res - 1;
    if(data->point.y >= drv->disp->driver->ver_res)
      data->point.y = drv->disp->driver->ver_res - 1;`

**Comment by kisvegabor** [comment]
Thanks for the report. It was changed in LVGL v8.

Can you a PR to fix it?
