### ISSUE TITLE
libinput touch driver assumes fullscreen display

### ISSUE THREAD

**Issue by Johennes** [lvgl/lv_drivers#166]
I've been swamping you folks with PRs lately so I thought I'd write this one up as an issue first before sending yet another PR. :slightly_smiling_face: 

I ran into this when following up on #164. As described in that pull request, I'm working on a framebuffer application that covers only part of the screen and leaves the rest of it untouched for other programs to use. When trying this out on a touch screen, I noticed that the libinput touch driver uses `LV_HOR_RES` and `LV_VER_RES` to transform the touch to screen coordinates.

```
case LIBINPUT_EVENT_TOUCH_MOTION:
case LIBINPUT_EVENT_TOUCH_DOWN:
  touch_event = libinput_event_get_touch_event(event);
  most_recent_touch_point.x = libinput_event_touch_get_x_transformed(touch_event, LV_HOR_RES);
  most_recent_touch_point.y = libinput_event_touch_get_y_transformed(touch_event, LV_VER_RES);
  libinput_button = LV_INDEV_STATE_PR;
  break;
```

When the display size is reduced with the API introduced in #164, however, that means touches outside of the actual display area are proportionally mapped into the display area. Or in other words, the touch is registered in a different place than the one you touched.

I found a way to fix this by injecting the full screen size and display offset into the driver:

```
case LIBINPUT_EVENT_TOUCH_MOTION:
case LIBINPUT_EVENT_TOUCH_DOWN: {
  touch_event = libinput_event_get_touch_event(event);
  lv_coord_t y = libinput_event_touch_get_y_transformed(touch_event, full_display_height) - display_y_offset;
  if (y < 0) {
    break; /* ignore touches that are out of bounds */
  }
  most_recent_touch_point.x = libinput_event_touch_get_x_transformed(touch_event, LV_HOR_RES);
  most_recent_touch_point.y = y;
  state->button = LV_INDEV_STATE_PR;
  break;
```

I'm curious if you'd accept a corresponding contribution. We could default `full_display_height` to `LV_VER_RES` and `display_y_offset` to 0 so that no client change is required if you're using a fullscreen display.

**Comment by kisvegabor** [comment]
I'm happy about your PRs. And knowing about your use cases help a lot to see which point of LVGL should be more flexible.

This issues seems more generic and maybe we can handle it inside lvgl too. 

If LVGL knew about the real display size and offset, we can add the offset to the `area` parameter in `flush_cb`, and the rendered area can be truncated to the real display size in LVGL, if the LVGL's draw area is positioned out of the display by the offset.

So I wonder if it makes sens to add 4 parameters to `lv_disp_drv_t`:
- display_hor_res
- display_ver_res
- offset_x
- offset_y

These parameters are available form the `indev_drv` as `indev_drv->disp->driver`.

I'm not sure if all these are required and it's the best way to approach this problem. I'm just thinking aloud :slightly_smiling_face:

**Comment by Johennes** [comment]
That is an interesting idea! I gave this a quick shot and at it does actually seem to work really well with only very little changes required. I pushed https://github.com/lvgl/lvgl/pull/2583 as a basis for further discussion.
