### ISSUE TITLE
Win32: ShellScalingApi.h not available on MinGW targets

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lv_drivers#170]
@MouriNaruto I am trying to update the CodeBlocks project to the latest version of the Win32 driver, however, I'm getting an error that  `ShellScalingApi.h` is missing.

According to [this issue](https://github.com/cycfi/elements/issues/9), it seems that it's either not available or missing some APIs when using GCC to compile. Could you take a look when you have some time, please?

**Comment by MouriNaruto** [comment]
Got it. I will do some changes in recent days.
