### ISSUE TITLE
FTBFS: some drivers use old API

### ISSUE THREAD

**Issue by rzr** [lvgl/lv_drivers#174]
```
./display/ST7565.c:#include "lvgl/lv_core/lv_vdb.h"
./display/R61581.c:#include "lvgl/lv_core/lv_vdb.h"
```

It looks like lv_vdb.h header has been removed in  v5.3-36-g673892cd8

https://github.com/lvgl/lvgl/commit/673892cd8092625303f1baf7cd931cfa0b9e14b4#diff-790ed79ef48d3d6e063ccd7d85aaaa612d7a08cd319af32cf21485134ac71c97

**Comment by kisvegabor** [comment]
I close this
