### ISSUE TITLE
lv_win32_display_driver_flush_callback only handles screen-sized display buffers

### ISSUE THREAD

**Issue by pokemaniak** [lvgl/lv_drivers#185]
Hello,

While digging into the [Windows Visual Studio Simulator](https://github.com/lvgl/lv_sim_visual_studio), I found out that the simulator always refreshes the entire screen whenever anything is marked as dirty, which leads to atrocious performances. As far as I know, this may be a choice, but I really wanted to refresh only part of the screen on the Windows simulator, so that's what I did. The reason I mention this here is that part of the fix that was required is located in this repository, in [win32drv.c](https://github.com/lvgl/lv_drivers/blob/master/win32drv/win32drv.c).

The problem I see is [here](https://github.com/lvgl/lv_drivers/blob/99d83c960e3370ec450c5427583c4823effda041/win32drv/win32drv.c#L677-L682). As far as I understood, `g_pixel_buffer` contains the pixels of the entire screen, while `color_p` contains the information on a particular area (potentially smaller than the screen). Why use a `memcpy` directly? Say I use `LV_COLOR_DEPTH == 32`, this means that the drawing will be correct only if the input `color_p` contains the entire screen. Otherwise, the pixels will always be crammed into the upper-left corner and shapes will be distorted if the width of `colour_p` doesn't match the screen width. Also `area` is an unused parameter even though it contains the bounding box of the input area, which should certainly be used...

It is worth mentioning that replacing the mentioned lines with [those](https://github.com/lvgl/lv_drivers/blob/99d83c960e3370ec450c5427583c4823effda041/win32drv/win32drv.c#L696-L703) works like a charm for me. That may not be a good solution, but it goes to show that it can be fixed (assuming it is indeed an issue).

Is there a good reason I'm not getting for this choice, or is this an issue that I can propose to fix?

Best,
Alex.

Edit: I do realise that [this line](https://github.com/lvgl/lv_drivers/blob/99d83c960e3370ec450c5427583c4823effda041/win32drv/win32drv.c#L344) (along with the definition of [lv_win32_display_driver_rounder_callback](https://github.com/lvgl/lv_drivers/blob/99d83c960e3370ec450c5427583c4823effda041/win32drv/win32drv.c#L742-L750)) means that the `color_p` input of `lv_win32_display_driver_flush_callback` will always be screen-sized, but that's part of the problem; it forces a full screen refresh when anything is invalidated.

**Comment by pokemaniak** [comment]
I see, thank you for the information.

So I investigated a bit, turns out using a large resized background image and only a few widgets is much more cpu intensive when the entire screen has to be refreshed every time... But that is very specific, so I can see why the current solution is better in most cases (including in the benchmark, where many objects are moving).

Just tell me if you want to investigate further or if I should close the issue.

**Comment by MouriNaruto** [comment]
@pokemaniak 

For old win_drv implementation, it tries to refresh only part of the screen, it creates Windows GDI Compatible Bitmap Object every flush because the image size of every flush is different. It causes every flush we need to make a lot of context mode switch via calling a lot of system calls internally. @embeddedt knows the performance about win_drv implementation. (I uses win_drv I feel it really slow, so this is why I create the win32drv driver.)

The win32drv driver don't need to create Windows GDI Compatible Bitmap Object every flush. It reduces the overhead via reducing system calls and improve the performance, even always refreshes the entire screen every flush.

Kenji Mouri

**Comment by embeddedt** [comment]
I can confirm that @MouriNaruto's approach is significantly more performant than mine (I was the original creator of the win_drv driver) in the vast majority of cases. Mine was really a quick implementation meant to remove the dependency on SDL for Windows developers, as SDL tends to be difficult to install there.
