### ISSUE TITLE
Wayland: how go fullscreen

### ISSUE THREAD

**Issue by fhelie-infinition** [lvgl/lv_drivers#191]
How to set the screen to go fullscreen with the wayland driver. 
There is a top bar with date and time that I want to remove from the screen.

Thanks

**Comment by kisvegabor** [comment]
@WallaceIT made a major improvement on the Wayland driver.
 
Francesco, could you take a look?

**Comment by WallaceIT** [comment]
Hello,

fullscreen has not been implemented yet, though it should not be too difficult. I'll try to take a look at it during the weekend.

**Comment by fhelie-infinition** [comment]
Thank you, I will give it a try!

**Comment by WallaceIT** [comment]
Opened pull request #196 on the subject

**Comment by kisvegabor** [comment]
The PR is merged so I close thi sissue.
