### ISSUE TITLE
ESP-IDF & Arduino samples for WT32-SC01 using LVGL8 + LOVYANGFX 

### ISSUE THREAD

**Issue by sukesh-ak** [lvgl/lv_drivers#199]
After struggling to get LVGL 8.x working with the drivers here, finally switched to LovyanGFX for display & touch drivers.
Thank you! Love lvgl!

*ESP-IDF & Arduino samples for WT32-SC01 using LVGL8 + LOVYANGFX*

Device : WT32-SC01 
Display / Touch Drivers : LovyanGFX
Widgets : LVGL 8.x

ESP-IDF => WT32-SC01 + LVGL8 + LOVYANGFX 
https://github.com/sukesh-ak/LVGL8-WT32-SC01-IDF

Arduino => WT32-SC01 + LVGL8 + LOVYANGFX 
https://github.com/sukesh-ak/LVGL8-WT32-SC01-Arduino

**Comment by kisvegabor** [comment]
Hi,

Sorry, it seems wasn't notified about this issue. I hope LOVYANGFX can be be integrated into our new driver architecture plan. 


I close this issue now, feel free to comment in https://github.com/lvgl/lvgl/issues/2720 if you can remarks about the integration.
