### ISSUE TITLE
win32drv poor keyboard functionality

### ISSUE THREAD

**Issue by wrgallo** [lvgl/lv_drivers#254]
Currently the `win32drv` keyboard driver wouldn't support lots of keys, such as `"+-*/[];',./\!@#$%^&*()_+~"`, also the letters `"A-Z"` would always become lower-case regardless of the current state of `shift` and `caps-lock` keys.

I am already working on the pull-request to fix this issue.

**Comment by MouriNaruto** [comment]
@kisvegabor It's bug I can reproduce. I will fix it ASAP.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@wrgallo Your issue have been fixed. I will create a PR.

![image](https://user-images.githubusercontent.com/10867563/205047767-84b75987-5084-422c-ab77-12b5d26220f1.png)

Kenji Mouri
