### ISSUE TITLE
win32drv Possibility to change the window title for each display

### ISSUE THREAD

**Issue by wrgallo** [lvgl/lv_drivers#256]
Currently by creating a display window with `lv_win32_init` the created window will have the title `L"LVGL Simulator for Windows Desktop"`, that string cannot be easily changed by user.

I am already working on a pull request to fix this issue.

**Comment by kisvegabor** [comment]
@MouriNaruto could you take look at it?

**Comment by kisvegabor** [comment]
Thank you!

**Comment by MouriNaruto** [comment]
@kisvegabor 

The issue is also solved by https://github.com/lvgl/lv_drivers/pull/259.

Kenji Mouri

**Comment by kisvegabor** [comment]
Great, I close it then.
