### ISSUE TITLE
Convert drivers from lvgl_esp32_drivers to a generic format

### ISSUE THREAD

**Issue by Guichaguri** [lvgl/lv_drivers#266]
This project has a few drivers that can be used in any microcontroller, only by writing a configuration file.

There is also the `lvgl_esp32_drivers` repository which has a lot more drivers, but they are only for ESP32 MCUs.

Are there any plans to bring those drivers to this repository, changing esp32-specific functions to the generic ones? Also, are contributions to convert those drivers being accepted?

Thank you!

**Comment by kisvegabor** [comment]
We will move all driver directly into the `lvgl` repo in the next major version (v9). I'm a little bit busy with some projects now but I hope I can back to its development soon.
