### ISSUE TITLE
SDL crashes under certain comditions in `8.3.0`

### ISSUE THREAD

**Issue by vshymanskyy** [lvgl/lv_drivers#281]
https://github.com/lvgl/lv_drivers/blob/57494ff8ec012fb6ea0a6d2e3c9485bace392d34/sdl/sdl.c#L370-L371

Looks like `_lv_refr_get_disp_refreshing` can return NULL during the app startup.
changing second line to `if(d && d->driver && d->driver->screen_transp)` helped in my case

**Comment by kisvegabor** [comment]
Makes sense, could send a Pull request?

**Comment by mikaeladlers** [comment]
I have the same issue and have created a pull request

**Comment by kisvegabor** [comment]
#286 is merged, closing this issue.
