### ISSUE TITLE
[RK3568 waylay drivce] interface 'xdg_toplevel' has no event 3

### ISSUE THREAD

**Issue by eYoung8475** [lvgl/lv_drivers#302]
Using the rk3568 development board, driven by wayland （version 1.22.0）, with a prompt of "interface 'xdg_toplevel' has no event 3" and no GUI displayed。[
![image](https://github.com/lvgl/lv_drivers/assets/50727129/439d994d-7508-40d7-8320-54a66e4b024b)
](url)

**Comment by arilink** [comment]
请问这个有进展吗

**Comment by arilink** [comment]
Is there any progress on this issue? I am also trying to run LVGL on rk3568

**Comment by eYoung8475** [comment]
No, contacting Rockchip is currently unable to resolve the issue. It may be necessary to replace the DRM or x11 display

**Comment by kisvegabor** [comment]
I would be also happy contact Rockchip. Hopefully we could collaborate somehow to make it easier to get started with Rockchip and LVGL. Could you write an introduction email to me and you contact person at Rockchip?

**Comment by kisvegabor** [comment]
Thank you! 
We are onboarding some new chip vendors, but I'll contact them when we will have a little bit free capacity.

**Comment by eYoung8475** [comment]
Just tested it, The wayland on rk3568 is now working properly.

**Comment by eYoung8475** [comment]
Test on patch 110089d in the master branch。

**Comment by kisvegabor** [comment]
Great, I close this issue then.
